name: Test
on: [push]
jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP CodeSniffer
        uses: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      - name: phpcs
        run: phpcs ./src/
