name: Test
on: [push]
jobs:
  demo:
    name: Phpcs
    runs-on: ubuntu-latest
  steps:
    -uses: actions/checkout@v2
    -uses: shivammathur/setup-php@v2
    with:
      php-version: 8.0
    -run: composer validate --strict

    #  - name: Install dependencies
    #     run: composer install --no-progress --optimize-autoloader

    #   - name: Run CS checks
    #     run: composer cs-check

    #   -run: phpcs .
